<a href="https://colab.research.google.com/github/lukewilliams16/ai-ml-portfolio/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [4]:
# 0-D tensor (scalar)
scalar = tf.constant(5)
print(scalar)

# 1-D tensor (vector)
vector = tf.constant([1, 2, 3])
print(vector)

# 2-D tensor (matrix)
matrix = tf.constant([[1, 2], [3, 4]])
print(matrix)

# 3-D tensor
tensor3d = tf.constant([[[1], [2]], [[3], [4]]])
print(tensor3d)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


In [8]:
matrix = tf.constant(tf.range(1,10), shape=(3,3))
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [9]:
mat1 = tf.constant([[1, 2], [3, 4]])
mat2 = tf.constant([[5, 6], [7, 8]])

In [11]:
print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 * mat2)
print(mat1 / mat2)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


In [12]:
print(tf.matmul(mat1, mat2))

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [15]:
print(tf.reduce_sum(mat1))
print(tf.reduce_mean(mat1))

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [16]:
transosed=tf.transpose(mat1)
transosed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>